### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by yanghaoRonin** [IDKiro/gUNet#6]
Traceback (most recent call last):
  File "D:/Edge_Downloade/gUNet-main/gUNet-main/train.py", line 213, in <module>
    main()
  File "D:/Edge_Downloade/gUNet-main/gUNet-main/train.py", line 172, in main
    sampler=DistributedSampler(val_dataset, shuffle=False),		# comment this line for more accurate validation
  File "D:\anaconda\envs\Other\lib\site-packages\torch\utils\data\distributed.py", line 66, in __init__
    num_replicas = dist.get_world_size()
  File "D:\anaconda\envs\Other\lib\site-packages\torch\distributed\distributed_c10d.py", line 867, in get_world_size
    return _get_group_size(group)
  File "D:\anaconda\envs\Other\lib\site-packages\torch\distributed\distributed_c10d.py", line 325, in _get_group_size
    default_pg = _get_default_group()
  File "D:\anaconda\envs\Other\lib\site-packages\torch\distributed\distributed_c10d.py", line 429, in _get_default_group
    raise RuntimeError(
RuntimeError: Default process group has not been initialized, please make sure to call init_process_group.

**Comment by IDKiro** [comment]
I have not tried it on windows, but it seems that you did not use right script.

**Comment by yanghaoRonin** [comment]
> 

I followed your introduction, used train.py to train a custom dataset, and just got an error

**Comment by IDKiro** [comment]
You can try disable distributed training:

```
python train.py --model gunet_b --train_set ITS --val_set SOTS-IN --exp reside-in --use_mp
```

I have not written code in the Windows environment for a long time, you can search for the problem on stackoverflow.

**Comment by yanghaoRonin** [comment]
thanks you，I will try !

**Comment by IDKiro** [comment]
reopen if necessary

**Comment by yanghaoRonin** [comment]
If that's the case, it would be very appreciated
